# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2018-01-13 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='description',
            field=models.CharField(max_length=80),
        ),
    ]
