# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-29 23:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=80)),
                ('age', models.IntegerField()),
                ('country', models.CharField(max_length=80)),
                ('producer', models.CharField(max_length=80)),
                ('image', models.ImageField(default='media/fit_service_img9.jpg', max_length=255, upload_to='photos/')),
                ('duration', models.IntegerField(default=0)),
                ('genre', models.CharField(default='', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('num_rows', models.IntegerField()),
                ('num_columns', models.IntegerField()),
                ('is_valid', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('cost', models.IntegerField()),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Film')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Hall')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField()),
                ('row', models.IntegerField()),
                ('is_free', models.BooleanField(default=True)),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Seance')),
            ],
        ),
    ]
